#!/bin/sh -efu

arch="$1"; shift

. gb-sh-functions

rm -rf "build/repo/$arch"

for i in $(src_nums); do
	$0-i "$arch" "$i" || {
		rc=$?
		# no need to force task rebuild if abort
		[ -f task/abort ] ||
			echo "$i" >"build/force-rebuild-$arch"
		exit $rc
	}
done
